# Generated by Django 5.1.4 on 2025-01-09 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0002_bookmodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='author',
        ),
    ]
